// Code generated by MockGen. DO NOT EDIT.
// Source: strategy.go
//
// Generated by this command:
//
//	mockgen -source=strategy.go -destination=mocks/mock_strategy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	engine "github.com/user/nt/internal/engine"
	model "github.com/user/nt/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStrategyEvaluator is a mock of StrategyEvaluator interface.
type MockStrategyEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyEvaluatorMockRecorder
	isgomock struct{}
}

// MockStrategyEvaluatorMockRecorder is the mock recorder for MockStrategyEvaluator.
type MockStrategyEvaluatorMockRecorder struct {
	mock *MockStrategyEvaluator
}

// NewMockStrategyEvaluator creates a new mock instance.
func NewMockStrategyEvaluator(ctrl *gomock.Controller) *MockStrategyEvaluator {
	mock := &MockStrategyEvaluator{ctrl: ctrl}
	mock.recorder = &MockStrategyEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategyEvaluator) EXPECT() *MockStrategyEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockStrategyEvaluator) Evaluate(session model.Session, configStr string) []engine.Signal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", session, configStr)
	ret0, _ := ret[0].([]engine.Signal)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockStrategyEvaluatorMockRecorder) Evaluate(session, configStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockStrategyEvaluator)(nil).Evaluate), session, configStr)
}
