// Code generated by MockGen. DO NOT EDIT.
// Source: signal_repo.go
//
// Generated by this command:
//
//	mockgen -source=signal_repo.go -destination=mocks/mock_signal.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/user/nt/internal/model"
	repository "github.com/user/nt/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockStrategySignalRepository is a mock of StrategySignalRepository interface.
type MockStrategySignalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStrategySignalRepositoryMockRecorder
	isgomock struct{}
}

// MockStrategySignalRepositoryMockRecorder is the mock recorder for MockStrategySignalRepository.
type MockStrategySignalRepositoryMockRecorder struct {
	mock *MockStrategySignalRepository
}

// NewMockStrategySignalRepository creates a new mock instance.
func NewMockStrategySignalRepository(ctrl *gomock.Controller) *MockStrategySignalRepository {
	mock := &MockStrategySignalRepository{ctrl: ctrl}
	mock.recorder = &MockStrategySignalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategySignalRepository) EXPECT() *MockStrategySignalRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStrategySignalRepository) Create(ctx context.Context, s *model.StrategySignal) (*model.StrategySignal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(*model.StrategySignal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStrategySignalRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStrategySignalRepository)(nil).Create), ctx, s)
}

// GetGridInsights mocks base method.
func (m *MockStrategySignalRepository) GetGridInsights(ctx context.Context, symbol string, userID int64) ([]repository.GridInsight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGridInsights", ctx, symbol, userID)
	ret0, _ := ret[0].([]repository.GridInsight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGridInsights indicates an expected call of GetGridInsights.
func (mr *MockStrategySignalRepositoryMockRecorder) GetGridInsights(ctx, symbol, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGridInsights", reflect.TypeOf((*MockStrategySignalRepository)(nil).GetGridInsights), ctx, symbol, userID)
}

// GetSummary mocks base method.
func (m *MockStrategySignalRepository) GetSummary(ctx context.Context, sessionID int64) (*model.SignalSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, sessionID)
	ret0, _ := ret[0].(*model.SignalSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockStrategySignalRepositoryMockRecorder) GetSummary(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockStrategySignalRepository)(nil).GetSummary), ctx, sessionID)
}

// ListBySession mocks base method.
func (m *MockStrategySignalRepository) ListBySession(ctx context.Context, sessionID int64, limit int) ([]model.StrategySignal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySession", ctx, sessionID, limit)
	ret0, _ := ret[0].([]model.StrategySignal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySession indicates an expected call of ListBySession.
func (mr *MockStrategySignalRepositoryMockRecorder) ListBySession(ctx, sessionID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySession", reflect.TypeOf((*MockStrategySignalRepository)(nil).ListBySession), ctx, sessionID, limit)
}

// ListPending mocks base method.
func (m *MockStrategySignalRepository) ListPending(ctx context.Context, sessionID int64) ([]model.StrategySignal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, sessionID)
	ret0, _ := ret[0].([]model.StrategySignal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockStrategySignalRepositoryMockRecorder) ListPending(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockStrategySignalRepository)(nil).ListPending), ctx, sessionID)
}

// UpdateValidation mocks base method.
func (m *MockStrategySignalRepository) UpdateValidation(ctx context.Context, id int64, status string, resultPct, resultGridSteps, maxFavPct, maxAdvPct, maxFavGrid, maxAdvGrid float64, note string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateValidation", ctx, id, status, resultPct, resultGridSteps, maxFavPct, maxAdvPct, maxFavGrid, maxAdvGrid, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateValidation indicates an expected call of UpdateValidation.
func (mr *MockStrategySignalRepositoryMockRecorder) UpdateValidation(ctx, id, status, resultPct, resultGridSteps, maxFavPct, maxAdvPct, maxFavGrid, maxAdvGrid, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateValidation", reflect.TypeOf((*MockStrategySignalRepository)(nil).UpdateValidation), ctx, id, status, resultPct, resultGridSteps, maxFavPct, maxAdvPct, maxFavGrid, maxAdvGrid, note)
}
