// Code generated by MockGen. DO NOT EDIT.
// Source: session_repo.go
//
// Generated by this command:
//
//	mockgen -source=session_repo.go -destination=mocks/mock_session.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/user/nt/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, s *model.Session) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockSessionRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockSessionRepository) FindByID(ctx context.Context, id int64) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSessionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSessionRepository)(nil).FindByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockSessionRepository) ListByUser(ctx context.Context, userID int64) ([]model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockSessionRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockSessionRepository)(nil).ListByUser), ctx, userID)
}

// ListByUserAndStrategy mocks base method.
func (m *MockSessionRepository) ListByUserAndStrategy(ctx context.Context, userID int64, strategy string) ([]model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserAndStrategy", ctx, userID, strategy)
	ret0, _ := ret[0].([]model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserAndStrategy indicates an expected call of ListByUserAndStrategy.
func (mr *MockSessionRepositoryMockRecorder) ListByUserAndStrategy(ctx, userID, strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserAndStrategy", reflect.TypeOf((*MockSessionRepository)(nil).ListByUserAndStrategy), ctx, userID, strategy)
}

// ListRunning mocks base method.
func (m *MockSessionRepository) ListRunning(ctx context.Context) ([]model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunning", ctx)
	ret0, _ := ret[0].([]model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRunning indicates an expected call of ListRunning.
func (mr *MockSessionRepositoryMockRecorder) ListRunning(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunning", reflect.TypeOf((*MockSessionRepository)(nil).ListRunning), ctx)
}

// Update mocks base method.
func (m *MockSessionRepository) Update(ctx context.Context, s *model.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSessionRepositoryMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionRepository)(nil).Update), ctx, s)
}

// UpdateStartedAt mocks base method.
func (m *MockSessionRepository) UpdateStartedAt(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStartedAt", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStartedAt indicates an expected call of UpdateStartedAt.
func (mr *MockSessionRepositoryMockRecorder) UpdateStartedAt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStartedAt", reflect.TypeOf((*MockSessionRepository)(nil).UpdateStartedAt), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockSessionRepository) UpdateStatus(ctx context.Context, id int64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSessionRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSessionRepository)(nil).UpdateStatus), ctx, id, status)
}

// UpdateStoppedAt mocks base method.
func (m *MockSessionRepository) UpdateStoppedAt(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStoppedAt", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStoppedAt indicates an expected call of UpdateStoppedAt.
func (mr *MockSessionRepositoryMockRecorder) UpdateStoppedAt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStoppedAt", reflect.TypeOf((*MockSessionRepository)(nil).UpdateStoppedAt), ctx, id)
}
