package engine

// Signal represents a trading signal generated by a strategy evaluation.
type Signal struct {
	SessionID int64  `json:"session_id"`
	Symbol    string `json:"symbol"`
	Side      string `json:"side"` // "buy" | "sell"
	Price     string `json:"price"`
	Quantity  string `json:"quantity"`
	Reason    string `json:"reason"` // e.g. "grid_level", "golden_cross", "dca_interval"
	Timestamp int64  `json:"timestamp"`
}

// GridConfig defines the parameters for the grid trading strategy.
type GridConfig struct {
	UpperPrice float64 `json:"upper_price"` // highest price in the grid range
	LowerPrice float64 `json:"lower_price"` // lowest price in the grid range
	GridCount  int     `json:"grid_count"`  // number of price levels between lower and upper
	Quantity   string  `json:"quantity"`    // base asset amount per order
}

// TrendConfig defines the parameters for the SMA crossover strategy.
type TrendConfig struct {
	FastPeriod              int     `json:"fast_period"`          // short SMA period (e.g. 10)
	SlowPeriod              int     `json:"slow_period"`          // long SMA period (e.g. 30)
	Interval                string  `json:"interval,omitempty"`   // "5m","15m","1h","4h"; default "5m"
	Quantity                string  `json:"quantity"`             // base asset amount per order
	Capital                 float64 `json:"capital,omitempty"`    // optional: capital -> quantity
	Horizon                 string  `json:"horizon,omitempty"`    // "short","medium","long"
	ValidationMode          string  `json:"validation_mode,omitempty"`           // trend: always "percent"
	ValidationTargetValue   float64 `json:"validation_target_value,omitempty"`
	ValidationInvalidValue  float64 `json:"validation_invalid_value,omitempty"`
	ValidationWindowMinutes int     `json:"validation_window_minutes,omitempty"`
}

// DCAConfig defines the parameters for the Dollar-Cost Average strategy.
type DCAConfig struct {
	IntervalSec   int     `json:"interval_sec"`    // seconds between buys (e.g. 3600 = 1h)
	Amount        string  `json:"amount"`          // quote asset amount per buy (e.g. "10" USDT)
	TakeProfitPct float64 `json:"take_profit_pct"` // sell trigger: price >= avg_buy * (1 + pct/100), 0 = disabled
	StopLossPct   float64 `json:"stop_loss_pct"`   // sell trigger: price <= avg_buy * (1 - pct/100), 0 = disabled
	DropPct       float64 `json:"drop_pct"`        // buy trigger: price <= last_buy * (1 - pct/100), 0 = disabled (interval only)
}
